apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-mysql
  labels:
    app: example-app
    name: simple-webapp-mysql
spec:
  containers:
   - name: simple-webapp-mysql
     image: 089664965210.dkr.ecr.us-east-1.amazonaws.com/cloud9:latest
     ports:
     - containerPort: 8080
    #Volume Mount
     volumeMounts:
     - name: app-secret-volumes
       mountPath: /opt/app-secret-volumes
       readOnly: true
     envFrom:
      - secretRef:
          name: app-secret
    #Volume Mount for ConfigMap
     volumeMounts:
      - name: config-volume
        mountPath: /opt/clo835/config/image_url
  #volume for secret
  volumes:
    - name: app-secret-volumes
      secret:
        secretName: app-secret
  #volume for ConfigMap
  volumes:
    - name: config-volume
      configMap:
        name: config-bgimage
  
